### ISSUE TITLE
[RD Music Player][v1.2]Sharing file feature is not working.

### ISSUE THREAD

**Issue by maaudrana** [dtrung98/MusicPlayer#3]
<h4>Actual behavior</h4>
I can not share songs from the app.After clicking share no response occure.
<h4>Expected behavior</h4>
Expected that i can share songs with my friends from the app.
<h4>How to reproduce</h4>
<ol>
<li>Install the apps and open the app</li>
<li>click songs icon</li>
<li>From the song list choose any song and click three horizontal dots of the song</li>
<li>Just click share</li>
<li>See the error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:v1.2</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/77N1aIvi12U">https://youtu.be/77N1aIvi12U</a>

**Comment by maaudrana** [comment]
hi @dtrung98  add bug lebel if this bug report is valid.so same thing for my other contribution tnx

**Comment by dtrung98** [comment]
Hi maaudrana.
I'm very happy when you have a try at my app. This app isn't completed yet, so many features you see are not available now. I am doing my best to have a full-feature app soon.
Anyway, thank you for your big support.
