### ISSUE TITLE
( MusicPlayer version 1.2 )  click on lyric button, the application crash

### ISSUE THREAD

**Issue by waqaranwar888** [dtrung98/MusicPlayer#9]
#### Project Information

* Repository: https://github.com/dtrung98/MusicPlayer

* Project Name:  MusicPlayer

* My GitHub Account : https://github.com/waqaranwar888

#### Expected behavior
While listening to the song, lyric should be displayed when I click the lyric button to find the lyric of this song.

#### Actual behavior

When I click the lyric button, the application crashed.

#### How to reproduce

1-download the application
2-Click on play in
3-Click on lyric button
4-Application crash 

* Browser/App version: 1.2
* Operating system: 6.0.1

#### Recording Of The Bug
![20190717_171135](https://user-images.githubusercontent.com/52924148/61376790-503c7180-a8bb-11e9-8982-4a65d255a3a3.gif)

# Logcat 

<pre><code>07-17 17:42:48.633 23027 23027 D AndroidRuntime: Shutting down VM

07-17 17:42:48.643 23027 23027 E AndroidRuntime: FATAL EXCEPTION: main

07-17 17:42:48.643 23027 23027 E AndroidRuntime: Process: com.ldt.musicr, PID: 23027

07-17 17:42:48.643 23027 23027 E AndroidRuntime: java.lang.IllegalStateException: Required view 'description' with ID 2131361939 for field 'mDescription' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at butterknife.internal.Utils.findRequiredView(Utils.java:88)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at butterknife.internal.Utils.findRequiredViewAsType(Utils.java:100)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at com.ldt.musicr.ui.bottomsheet.LyricBottomSheet_ViewBinding.<init>(LyricBottomSheet_ViewBinding.java:63)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Native Method)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at butterknife.ButterKnife.bind(ButterKnife.java:171)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at com.ldt.musicr.ui.bottomsheet.LyricBottomSheet.onViewCreated(LyricBottomSheet.java:132)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7406)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

07-17 17:42:48.643 23027 23027 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
</code></pre>

**Comment by dtrung98** [comment]
Hi, I fixed it.
[Newest Apk](https://github.com/dtrung98/Source/raw/master/music_player_v17_15.apk)

Thank you

**Comment by waqaranwar888** [comment]
Bug Fix 

Thank you
